const $=(s)=>document.querySelector(s);const $$=(s)=>Array.from(document.querySelectorAll(s));
let metric=3100;function animateNumber(){metric+=Math.round(Math.random()*7-2);$('#animatedNumber').textContent=metric.toLocaleString('en-US')}setInterval(animateNumber,1700);
let points=Array.from({length:55},(_,i)=>45+Math.sin(i/5)*18+Math.random()*8);function drawChart(){points=[...points.slice(1),Math.max(8,Math.min(92,points.at(-1)+(Math.random()-.45)*10))];const w=500,h=170;const d=points.map((p,i)=>`${i?'L':'M'}${(i/(points.length-1))*w},${h-(p/100)*h}`).join(' ');$('#liveChart').innerHTML=`<path d="M0,170 ${d} L500,170 Z" fill="rgba(6,37,64,.08)"/><path d="${d}" fill="none" stroke="#062540" stroke-width="4" stroke-linecap="round"/>`;}
setInterval(drawChart,900);drawChart();
function showToast(msg='Sonner-style notification rendered.'){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.hidden=true,2600)}$('#toastBtn').onclick=()=>showToast('Sonner: interaction saved.');
$$('.otp input').forEach((input,i,arr)=>{input.addEventListener('input',()=>{input.value=input.value.slice(-1).toUpperCase();if(input.value&&arr[i+1])arr[i+1].focus()});input.addEventListener('keydown',e=>{if(e.key==='Backspace'&&!input.value&&arr[i-1])arr[i-1].focus()})});
function updateLeva(){const radius=$('#radius').value,glow=$('#glow').value/100,density=+$('#density').value;const s=$('#controlledSurface');s.style.borderRadius=radius+'px';s.style.boxShadow=`0 30px 100px rgba(6,37,64,${glow})`;$('#particles').innerHTML=Array.from({length:density},()=>'<i></i>').join('')}['radius','glow','density'].forEach(id=>$('#'+id).addEventListener('input',updateLeva));updateLeva();
const commands=[['Profile','Professional summary','#profile'],['Libraries','All eight UI libraries','#libraries'],['Experience','Clinical and research timeline','#work'],['Publications','Original articles and chapters','#publications'],['NumberFlow','Animated counters','#libraries'],['input-otp','One-time passcode slots','#libraries'],['Liveline','Real-time charts','#libraries'],['Leva','GUI controls','#libraries'],['cmdk','Command palette','#libraries'],['Virtuoso','Virtualized feed','#work'],['dnd kit','Sortable priorities','#dragList'],['Sonner','Toast notifications','#toastBtn']];
function renderCommands(q=''){const list=commands.filter(c=>(c[0]+' '+c[1]).toLowerCase().includes(q.toLowerCase()));$('#commandResults').innerHTML=list.map((c,i)=>`<a class="command-item ${i===0?'active':''}" href="${c[2]}" data-name="${c[0]}"><b>${c[0]}</b><small>${c[1]}</small></a>`).join('')||'<div class="command-item"><b>No results</b></div>';$$('.command-item').forEach(a=>a.onclick=(e)=>{if(a.getAttribute('href')==='#toastBtn'){e.preventDefault();showToast('Sonner: command executed.')}closeCommand()})}
function openCommand(){const o=$('#commandOverlay');o.hidden=false;o.style.display='grid';$('#commandInput').value='';renderCommands();setTimeout(()=>$('#commandInput').focus(),20)}function closeCommand(){const o=$('#commandOverlay');o.hidden=true;o.style.display='none';}$('#openCommand').onclick=openCommand;$('#openCommand2').onclick=openCommand;$('#closeCommand').onclick=closeCommand;$('#commandOverlay').addEventListener('click',e=>{if(e.target.id==='commandOverlay')closeCommand()});$('#commandInput').addEventListener('input',e=>renderCommands(e.target.value));addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}if(e.key==='Escape')closeCommand()});
let dragged=null;$$('#dragList div').forEach(el=>{el.addEventListener('dragstart',()=>{dragged=el;el.classList.add('dragging')});el.addEventListener('dragend',()=>{el.classList.remove('dragging');showToast('dnd kit-style order updated.')});el.addEventListener('dragover',e=>{e.preventDefault();const list=$('#dragList');const after=[...list.querySelectorAll('div:not(.dragging)')].find(child=>e.clientY<child.getBoundingClientRect().top+child.offsetHeight/2);if(after)list.insertBefore(dragged,after);else list.appendChild(dragged)})});
